words = [
    "bbox",
    "bobinserters",
    "boblogistics",
    "factorio",
    "ibind",
    "inserter",
    "inserters",
    "localised",
    "nauvis",
    "neighbour",
    "neighbours",
    "pcall",
    "progressbar",
    "radiobutton",
]
